#!/bin/bash
# This script creates symbolic links to configurations
# stow utility must be installed separately

source stowdirs

for dir in ${STOW_DIRS[@]}; do
    echo "stow $dir"
    stow -D $dir
    stow $dir
done
